default_platform(:ios)
platform :ios do
  desc "Build and upload Vibe to TestFlight"
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
